// apps/web/src/routes/expert/sessions.tsx
import type { ExpertBookingScope } from "@repo/contracts/consultations";
import { createFileRoute } from "@tanstack/react-router";
import { CalendarCheckIcon } from "lucide-react";
import { useState } from "react";

import { PageShell } from "@/components/page-shell";
import { ProtectedPage } from "@/components/protected-page";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { WorkspaceHeading } from "@/components/workspace-heading";
import {
	useExpertBookings,
	useExpertDashboardSummary,
} from "@/hooks/use-consultations";
import { formatDate, formatTimeRange } from "@/lib/format";

export const Route = createFileRoute("/expert/sessions")({
	component: ExpertSessionsRoute,
	head: () => ({ meta: [{ title: "Expert Sessions | Laxiriir Expert" }] }),
});

function ExpertSessionsRoute() {
	return (
		<ProtectedPage requireApprovedExpert roles={["expert"]}>
			<PageShell>
				<ExpertSessions />
			</PageShell>
		</ProtectedPage>
	);
}

function ExpertSessions() {
	const [scope, setScope] = useState<ExpertBookingScope>("upcoming");
	const bookingsQuery = useExpertBookings(scope);
	const summaryQuery = useExpertDashboardSummary();
	const bookings = bookingsQuery.data?.bookings ?? [];

	return (
		<div className="flex flex-col gap-6">
			<WorkspaceHeading
				description="See confirmed upcoming consultations and your completed or cancelled history."
				eyebrow="Expert workspace"
				title="Sessions"
			/>
			<Tabs
				onValueChange={(value) =>
					setScope(value === "past" ? "past" : "upcoming")
				}
				value={scope}
			>
				<TabsList>
					<TabsTrigger value="upcoming">
						Upcoming ({summaryQuery.data?.upcomingBookings ?? 0})
					</TabsTrigger>
					<TabsTrigger value="past">
						Past ({summaryQuery.data?.pastBookings ?? 0})
					</TabsTrigger>
				</TabsList>
			</Tabs>
			{bookingsQuery.isError ? (
				<Alert variant="destructive">
					<AlertTitle>Unable to load sessions</AlertTitle>
					<AlertDescription>{bookingsQuery.error.message}</AlertDescription>
				</Alert>
			) : null}
			<div className="grid gap-3">
				{bookingsQuery.isPending ? (
					<>
						<Skeleton className="h-28" />
						<Skeleton className="h-28" />
					</>
				) : null}
				{!bookingsQuery.isPending && bookings.length === 0 ? (
					<Card>
						<CardContent className="flex flex-col items-center gap-3 py-12 text-center">
							<CalendarCheckIcon className="size-8 text-muted-foreground" />
							<p className="font-medium">No {scope} sessions</p>
							<p className="text-muted-foreground text-sm">
								{scope === "upcoming"
									? "Confirmed client bookings will appear here."
									: "Completed and cancelled sessions will appear here."}
							</p>
						</CardContent>
					</Card>
				) : null}
				{bookings.map((booking) => (
					<Card key={booking.id}>
						<CardContent className="flex flex-col justify-between gap-4 py-5 sm:flex-row sm:items-center">
							<div>
								<p className="font-semibold">
									{booking.client.displayName ?? "Client"}
								</p>
								<p className="text-muted-foreground text-sm">
									{formatDate(booking.startsAt, "full")} ·{" "}
									{formatTimeRange(booking.startsAt, booking.endsAt)}
								</p>
							</div>
							<Badge
								variant={
									booking.status === "cancelled" ? "secondary" : "default"
								}
							>
								{booking.status === "cancelled"
									? "Cancelled"
									: scope === "past"
										? "Completed"
										: "Confirmed"}
							</Badge>
						</CardContent>
					</Card>
				))}
			</div>
		</div>
	);
}

// apps/web/app/pages/client/sessions.vue
<script setup lang="ts">
import type { BookingDetail } from "@repo/platform/consultations";
import { Calendar, Clock } from "lucide-vue-next";

definePageMeta({
	layout: "client",
	clientSearchPlaceholder: "Search sessions...",
	middleware: ["auth-required", "verified-required", "role-required"],
	roles: ["client"],
});

useSeoMeta({
	title: "My Sessions | Laxiriir Expert",
});

const consultationApi = useConsultationApi();
const bookings = ref<BookingDetail[]>([]);
const loading = ref(true);
const errorMessage = ref("");
const activeFilter = ref<"all" | "upcoming" | "past">("all");

const filteredBookings = computed(() => {
	const now = new Date();
	if (activeFilter.value === "upcoming") {
		return bookings.value.filter((booking) => new Date(booking.startsAt) > now);
	}
	if (activeFilter.value === "past") {
		return bookings.value.filter((booking) => new Date(booking.endsAt) <= now);
	}
	return bookings.value;
});

onMounted(async () => {
	try {
		const response = await consultationApi.listBookings();
		bookings.value = response.bookings;
	} catch (error) {
		errorMessage.value =
			error instanceof Error ? error.message : "Unable to load your sessions.";
	} finally {
		loading.value = false;
	}
});

function formatDate(value: string) {
	return new Intl.DateTimeFormat(undefined, {
		dateStyle: "full",
	}).format(new Date(value));
}

function formatTimeRange(start: string, end: string) {
	const formatter = new Intl.DateTimeFormat(undefined, {
		hour: "numeric",
		minute: "2-digit",
	});
	return `${formatter.format(new Date(start))} – ${formatter.format(new Date(end))}`;
}
</script>

<template>
	<div class="space-y-6 p-4 sm:p-6 lg:p-8">
		<div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
			<div>
				<span class="home-kicker text-primary">Consultations</span>
				<h1 class="mt-1 font-display text-3xl font-bold tracking-tight">
					My sessions
				</h1>
				<p class="mt-1 text-sm text-muted-foreground">
					Every confirmed booking saved to your account.
				</p>
			</div>
			<NuxtLink
				to="/client/experts"
				class="inline-flex justify-center rounded-lg bg-primary px-4 py-2 text-sm font-bold text-primary-foreground"
			>
				Book a session
			</NuxtLink>
		</div>

		<p
			v-if="errorMessage"
			class="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive"
		>
			{{ errorMessage }}
		</p>

		<div class="flex gap-2">
			<button
				v-for="filter in ['all', 'upcoming', 'past'] as const"
				:key="filter"
				type="button"
				class="rounded-full px-4 py-2 text-xs font-semibold capitalize transition"
				:class="
					activeFilter === filter
						? 'bg-primary text-primary-foreground'
						: 'bg-secondary text-muted-foreground hover:text-foreground'
				"
				@click="activeFilter = filter"
			>
				{{ filter }}
			</button>
		</div>

		<div v-if="loading" class="py-16 text-center text-sm text-muted-foreground">
			Loading sessions...
		</div>
		<div
			v-else-if="filteredBookings.length === 0"
			class="rounded-xl border border-dashed border-border bg-card p-12 text-center"
		>
			<Calendar class="mx-auto size-8 text-primary" />
			<h2 class="mt-4 font-display text-lg font-semibold">No sessions found</h2>
			<p class="mt-1 text-sm text-muted-foreground">
				Book an available expert and the session will appear here.
			</p>
		</div>
		<div v-else class="space-y-4">
			<article
				v-for="booking in filteredBookings"
				:key="booking.id"
				class="flex flex-col justify-between gap-5 rounded-xl border border-border bg-card p-5 sm:flex-row sm:items-center"
			>
				<div class="flex items-center gap-4">
					<img
						:src="booking.expert.avatarUrl"
						:alt="booking.expert.displayName"
						class="size-14 rounded-xl object-cover ring-1 ring-border"
					/>
					<div>
						<h2 class="font-display text-lg font-semibold">
							{{ booking.expert.displayName }}
						</h2>
						<p class="text-sm text-primary">{{ booking.expert.title }}</p>
						<p class="mt-1 text-xs uppercase tracking-wide text-muted-foreground">
							{{ booking.status }}
						</p>
					</div>
				</div>

				<div class="space-y-1 text-sm sm:text-right">
					<p class="flex items-center gap-2 font-medium sm:justify-end">
						<Calendar class="size-4 text-primary" />
						{{ formatDate(booking.startsAt) }}
					</p>
					<p class="flex items-center gap-2 text-muted-foreground sm:justify-end">
						<Clock class="size-4" />
						{{ formatTimeRange(booking.startsAt, booking.endsAt) }}
					</p>
				</div>
			</article>
		</div>
	</div>
</template>
