// apps/web/app/pages/expert/calendar.vue
<script setup lang="ts">
import type { AvailabilitySlot } from "@repo/contracts/consultations";
import { CalendarDays, Clock3, Pencil, Plus, Trash2, X } from "lucide-vue-next";

definePageMeta({
	layout: false,
	middleware: [
		"auth-required",
		"verified-required",
		"role-required",
		"expert-approved-required",
	],
	roles: ["expert"],
});

useSeoMeta({
	title: "Availability | Laxiriir Expert",
});

const auth = useAuthStore();
const consultationApi = useConsultationApi();
const slots = ref<AvailabilitySlot[]>([]);
const startsAt = ref("");
const endsAt = ref("");
const editingSlotId = ref<number | null>(null);
const loading = ref(true);
const saving = ref(false);
const errorMessage = ref("");

function toLocalInput(value: Date | string) {
	const date = new Date(value);
	return new Date(date.getTime() - date.getTimezoneOffset() * 60_000)
		.toISOString()
		.slice(0, 16);
}

function resetForm() {
	const nextHour = new Date();
	nextHour.setMinutes(0, 0, 0);
	nextHour.setHours(nextHour.getHours() + 1);
	startsAt.value = toLocalInput(nextHour);
	endsAt.value = toLocalInput(new Date(nextHour.getTime() + 60 * 60 * 1000));
	editingSlotId.value = null;
}

async function loadSlots() {
	loading.value = true;
	errorMessage.value = "";
	try {
		slots.value = (await consultationApi.listOwnAvailability()).slots;
	} catch (error) {
		errorMessage.value =
			error instanceof Error ? error.message : "Unable to load availability.";
	} finally {
		loading.value = false;
	}
}

async function saveSlot() {
	if (!startsAt.value || !endsAt.value) return;
	saving.value = true;
	errorMessage.value = "";
	const input = {
		endsAt: new Date(endsAt.value).toISOString(),
		startsAt: new Date(startsAt.value).toISOString(),
	};

	try {
		if (editingSlotId.value === null) {
			await consultationApi.createAvailability(input);
		} else {
			await consultationApi.updateAvailability(editingSlotId.value, input);
		}
		resetForm();
		await loadSlots();
	} catch (error) {
		errorMessage.value =
			error instanceof Error ? error.message : "Unable to save availability.";
	} finally {
		saving.value = false;
	}
}

function editSlot(slot: AvailabilitySlot) {
	editingSlotId.value = slot.id;
	startsAt.value = toLocalInput(slot.startsAt);
	endsAt.value = toLocalInput(slot.endsAt);
	window.scrollTo({ behavior: "smooth", top: 0 });
}

async function deleteSlot(slot: AvailabilitySlot) {
	if (slot.booked || !window.confirm("Delete this availability slot?")) return;
	errorMessage.value = "";
	try {
		await consultationApi.deleteAvailability(slot.id);
		if (editingSlotId.value === slot.id) resetForm();
		await loadSlots();
	} catch (error) {
		errorMessage.value =
			error instanceof Error ? error.message : "Unable to delete availability.";
	}
}

function formatDate(value: string) {
	return new Intl.DateTimeFormat(undefined, {
		dateStyle: "medium",
	}).format(new Date(value));
}

function formatTime(value: string) {
	return new Intl.DateTimeFormat(undefined, {
		hour: "numeric",
		minute: "2-digit",
	}).format(new Date(value));
}

onMounted(async () => {
	await auth.ensureLoaded();
	resetForm();
	await loadSlots();
});
</script>

<template>
	<main class="min-h-screen bg-background text-foreground">
		<header class="border-b border-border bg-card">
			<div class="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8">
				<NuxtLink to="/expert" class="font-display text-lg font-bold">
					Laxiriir Expert
				</NuxtLink>
				<div class="text-right">
					<p class="text-sm font-semibold">{{ auth.user?.displayName }}</p>
					<p class="text-xs text-muted-foreground">Availability workspace</p>
				</div>
			</div>
		</header>

		<div class="mx-auto grid max-w-6xl gap-6 px-5 py-8 sm:px-8 lg:grid-cols-[360px_1fr]">
			<section class="h-fit rounded-2xl border border-border bg-card p-6 lg:sticky lg:top-6">
				<div class="flex items-center gap-3">
					<div class="rounded-xl bg-primary/10 p-2 text-primary">
						<Plus v-if="editingSlotId === null" class="size-5" />
						<Pencil v-else class="size-5" />
					</div>
					<div>
						<h1 class="font-display text-xl font-bold">
							{{ editingSlotId === null ? "Add availability" : "Edit availability" }}
						</h1>
						<p class="text-sm text-muted-foreground">Times use your local timezone.</p>
					</div>
				</div>

				<form class="mt-6 space-y-4" @submit.prevent="saveSlot">
					<label class="block space-y-2 text-sm font-medium">
						<span>Starts</span>
						<input
							v-model="startsAt"
							type="datetime-local"
							required
							class="w-full rounded-xl border border-input bg-background px-3 py-2.5 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
						/>
					</label>
					<label class="block space-y-2 text-sm font-medium">
						<span>Ends</span>
						<input
							v-model="endsAt"
							type="datetime-local"
							required
							class="w-full rounded-xl border border-input bg-background px-3 py-2.5 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
						/>
					</label>
					<div class="flex gap-2">
						<button
							type="submit"
							:disabled="saving"
							class="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-60"
						>
							{{ saving ? "Saving..." : editingSlotId === null ? "Add slot" : "Save changes" }}
						</button>
						<button
							v-if="editingSlotId !== null"
							type="button"
							class="rounded-xl border border-border p-2.5 text-muted-foreground hover:text-foreground"
							aria-label="Cancel editing"
							@click="resetForm"
						>
							<X class="size-5" />
						</button>
					</div>
				</form>
			</section>

			<section class="rounded-2xl border border-border bg-card p-6">
				<div class="flex items-center justify-between gap-4">
					<div>
						<h2 class="font-display text-xl font-bold">Your upcoming slots</h2>
						<p class="text-sm text-muted-foreground">Clients see every open slot listed here.</p>
					</div>
					<CalendarDays class="size-6 text-primary" />
				</div>

				<p
					v-if="errorMessage"
					class="mt-5 rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive"
				>
					{{ errorMessage }}
				</p>

				<div v-if="loading" class="py-12 text-center text-sm text-muted-foreground">
					Loading availability...
				</div>
				<div
					v-else-if="slots.length === 0"
					class="mt-6 rounded-2xl border border-dashed border-border bg-secondary/50 px-6 py-12 text-center"
				>
					<Clock3 class="mx-auto size-8 text-muted-foreground" />
					<p class="mt-3 font-semibold">No upcoming availability</p>
					<p class="mt-1 text-sm text-muted-foreground">Add your first slot to start accepting bookings.</p>
				</div>
				<div v-else class="mt-6 space-y-3">
					<article
						v-for="slot in slots"
						:key="slot.id"
						class="flex flex-col justify-between gap-4 rounded-xl border border-border p-4 sm:flex-row sm:items-center"
					>
						<div>
							<div class="flex items-center gap-2">
								<p class="font-semibold">{{ formatDate(slot.startsAt) }}</p>
								<span
									v-if="slot.booked"
									class="rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-bold uppercase text-primary"
								>
									Booked
								</span>
							</div>
							<p class="mt-1 text-sm text-muted-foreground">
								{{ formatTime(slot.startsAt) }}–{{ formatTime(slot.endsAt) }}
							</p>
						</div>
						<div class="flex gap-2">
							<button
								type="button"
								:disabled="slot.booked"
								class="rounded-lg border border-border p-2 text-muted-foreground hover:text-foreground disabled:cursor-not-allowed disabled:opacity-40"
								aria-label="Edit slot"
								@click="editSlot(slot)"
							>
								<Pencil class="size-4" />
							</button>
							<button
								type="button"
								:disabled="slot.booked"
								class="rounded-lg border border-destructive/30 p-2 text-destructive hover:bg-destructive/10 disabled:cursor-not-allowed disabled:opacity-40"
								aria-label="Delete slot"
								@click="deleteSlot(slot)"
							>
								<Trash2 class="size-4" />
							</button>
						</div>
					</article>
				</div>
			</section>
		</div>
	</main>
</template>

// apps/web/src/routes/expert/calendar.tsx
import type { AvailabilitySlot } from "@repo/contracts/consultations";
import { createFileRoute } from "@tanstack/react-router";
import { CalendarPlusIcon, PencilIcon, Trash2Icon } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { PageShell } from "@/components/page-shell";
import { ProtectedPage } from "@/components/protected-page";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
	AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/components/ui/card";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import {
	Empty,
	EmptyDescription,
	EmptyHeader,
	EmptyMedia,
	EmptyTitle,
} from "@/components/ui/empty";
import {
	Field,
	FieldDescription,
	FieldGroup,
	FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@/components/ui/table";
import { WorkspaceHeading } from "@/components/workspace-heading";
import {
	useCreateAvailability,
	useDeleteAvailability,
	useOwnAvailability,
	useUpdateAvailability,
} from "@/hooks/use-consultations";
import { formatDate, formatTime } from "@/lib/format";

export const Route = createFileRoute("/expert/calendar")({
	component: ExpertCalendarRoute,
	head: () => ({ meta: [{ title: "Availability | Laxiriir Expert" }] }),
});

function toIso(value: string) {
	return new Date(value).toISOString();
}

function toLocalInputValue(value: string) {
	const date = new Date(value);
	const localDate = new Date(
		date.getTime() - date.getTimezoneOffset() * 60_000,
	);
	return localDate.toISOString().slice(0, 16);
}

function ExpertCalendarRoute() {
	return (
		<ProtectedPage requireApprovedExpert roles={["expert"]}>
			<PageShell>
				<ExpertCalendar />
			</PageShell>
		</ProtectedPage>
	);
}

function ExpertCalendar() {
	const availabilityQuery = useOwnAvailability();
	const createMutation = useCreateAvailability();
	const updateMutation = useUpdateAvailability();
	const deleteMutation = useDeleteAvailability();
	const [startsAt, setStartsAt] = useState("");
	const [endsAt, setEndsAt] = useState("");
	const [editingSlot, setEditingSlot] = useState<AvailabilitySlot | null>(null);
	const [dialogOpen, setDialogOpen] = useState(false);
	const slots = availabilityQuery.data?.slots ?? [];
	const isSaving = createMutation.isPending || updateMutation.isPending;

	function resetForm() {
		setEditingSlot(null);
		setStartsAt("");
		setEndsAt("");
	}

	function addSlot() {
		resetForm();
		setDialogOpen(true);
	}

	function editSlot(slot: AvailabilitySlot) {
		setEditingSlot(slot);
		setStartsAt(toLocalInputValue(slot.startsAt));
		setEndsAt(toLocalInputValue(slot.endsAt));
		setDialogOpen(true);
	}

	async function saveSlot(event: React.FormEvent<HTMLFormElement>) {
		event.preventDefault();
		if (!startsAt || !endsAt || new Date(endsAt) <= new Date(startsAt)) {
			toast.error("End time must be after the start time.");
			return;
		}
		try {
			const input = { startsAt: toIso(startsAt), endsAt: toIso(endsAt) };
			if (editingSlot) {
				await updateMutation.mutateAsync({ input, slotId: editingSlot.id });
				toast.success("Availability updated.");
			} else {
				await createMutation.mutateAsync(input);
				toast.success("Availability added.");
			}
			resetForm();
			setDialogOpen(false);
		} catch (error) {
			toast.error(
				error instanceof Error ? error.message : "Unable to save availability.",
			);
		}
	}

	async function removeSlot(slot: AvailabilitySlot) {
		try {
			await deleteMutation.mutateAsync(slot.id);
			toast.success("Availability removed.");
		} catch (error) {
			toast.error(
				error instanceof Error
					? error.message
					: "Unable to remove availability.",
			);
		}
	}

	return (
		<div className="flex flex-col gap-6">
			<div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
				<WorkspaceHeading
					description="Create and manage the exact time slots clients can reserve."
					eyebrow="Expert workspace"
					title="Availability"
				/>
				<Button onClick={addSlot}>
					<CalendarPlusIcon data-icon="inline-start" />
					Add availability
				</Button>
			</div>
			<Dialog
				onOpenChange={(open) => {
					setDialogOpen(open);
					if (!open) resetForm();
				}}
				open={dialogOpen}
			>
				<DialogContent className="sm:max-w-xl">
					<DialogHeader>
						<DialogTitle>
							{editingSlot ? "Edit availability" : "Add availability"}
						</DialogTitle>
						<DialogDescription>
							Times use your device timezone. Overlapping or past slots are
							rejected by the server.
						</DialogDescription>
					</DialogHeader>
					<form className="flex flex-col gap-6" onSubmit={saveSlot}>
						<FieldGroup className="grid sm:grid-cols-2">
							<Field>
								<FieldLabel htmlFor="starts-at">Starts</FieldLabel>
								<Input
									id="starts-at"
									onChange={(event) => setStartsAt(event.target.value)}
									required
									type="datetime-local"
									value={startsAt}
								/>
							</Field>
							<Field>
								<FieldLabel htmlFor="ends-at">Ends</FieldLabel>
								<Input
									id="ends-at"
									onChange={(event) => setEndsAt(event.target.value)}
									required
									type="datetime-local"
									value={endsAt}
								/>
							</Field>
						</FieldGroup>
						<FieldDescription>
							Clients will immediately see an open slot after it is saved.
						</FieldDescription>
						<DialogFooter>
							<Button
								onClick={() => setDialogOpen(false)}
								type="button"
								variant="outline"
							>
								Cancel
							</Button>
							<Button disabled={isSaving} type="submit">
								{isSaving
									? "Saving…"
									: editingSlot
										? "Save changes"
										: "Add slot"}
							</Button>
						</DialogFooter>
					</form>
				</DialogContent>
			</Dialog>
			{availabilityQuery.isError ? (
				<Alert variant="destructive">
					<AlertTitle>Unable to load availability</AlertTitle>
					<AlertDescription>{availabilityQuery.error.message}</AlertDescription>
				</Alert>
			) : null}
			<Card>
				<CardHeader>
					<CardTitle>Your slots</CardTitle>
					<CardDescription>
						{slots.length} total availability slots.
					</CardDescription>
				</CardHeader>
				<CardContent>
					{availabilityQuery.isPending ? <Skeleton className="h-48" /> : null}
					{!availabilityQuery.isPending && slots.length > 0 ? (
						<div className="overflow-x-auto">
							<Table>
								<TableHeader>
									<TableRow>
										<TableHead>Date</TableHead>
										<TableHead>Time</TableHead>
										<TableHead>Status</TableHead>
										<TableHead className="text-right">Action</TableHead>
									</TableRow>
								</TableHeader>
								<TableBody>
									{slots.map((slot) => (
										<TableRow key={slot.id}>
											<TableCell>{formatDate(slot.startsAt)}</TableCell>
											<TableCell>
												{formatTime(slot.startsAt)} – {formatTime(slot.endsAt)}
											</TableCell>
											<TableCell>
												<Badge variant={slot.booked ? "default" : "secondary"}>
													{slot.booked ? "Booked" : "Open"}
												</Badge>
											</TableCell>
											<TableCell>
												{slot.booked ? (
													<span className="text-muted-foreground text-xs">
														Reserved
													</span>
												) : (
													<div className="flex justify-end gap-1">
														<Button
															onClick={() => editSlot(slot)}
															size="icon-sm"
															variant="ghost"
														>
															<PencilIcon />
															<span className="sr-only">Edit slot</span>
														</Button>
														<AlertDialog>
															<AlertDialogTrigger asChild>
																<Button size="icon-sm" variant="ghost">
																	<Trash2Icon />
																	<span className="sr-only">Delete slot</span>
																</Button>
															</AlertDialogTrigger>
															<AlertDialogContent>
																<AlertDialogHeader>
																	<AlertDialogTitle>
																		Delete this availability?
																	</AlertDialogTitle>
																	<AlertDialogDescription>
																		Clients will no longer be able to book this
																		time.
																	</AlertDialogDescription>
																</AlertDialogHeader>
																<AlertDialogFooter>
																	<AlertDialogCancel>
																		Keep slot
																	</AlertDialogCancel>
																	<AlertDialogAction
																		onClick={() => void removeSlot(slot)}
																	>
																		Delete
																	</AlertDialogAction>
																</AlertDialogFooter>
															</AlertDialogContent>
														</AlertDialog>
													</div>
												)}
											</TableCell>
										</TableRow>
									))}
								</TableBody>
							</Table>
						</div>
					) : null}
					{!availabilityQuery.isPending && slots.length === 0 ? (
						<Empty className="min-h-56 border">
							<EmptyHeader>
								<EmptyMedia variant="icon">
									<CalendarPlusIcon />
								</EmptyMedia>
								<EmptyTitle>No availability yet</EmptyTitle>
								<EmptyDescription>
									Add your first open time above so clients can book you.
								</EmptyDescription>
							</EmptyHeader>
						</Empty>
					) : null}
				</CardContent>
			</Card>
		</div>
	);
}
